# Generated by Django 4.2.2 on 2023-06-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155, verbose_name='Ismi')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram id')),
                ('language', models.IntegerField(blank=True, default=0, null=True, verbose_name='Til')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='Username')),
            ],
        ),
    ]
