# Generated by Django 4.1.7 on 2023-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon nomer')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram id')),
            ],
        ),
    ]
