# Generated by Django 4.2.2 on 2023-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='language',
        ),
        migrations.AddField(
            model_name='users',
            name='language_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
