# Generated by Django 4.2.2 on 2023-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_language_users_language_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language_id',
            field=models.IntegerField(default=0),
        ),
    ]
