# Generated by Django 4.2.2 on 2023-06-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_language_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='language_id',
            new_name='language',
        ),
    ]
