# Generated by Django 4.2.2 on 2023-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_language_id_users_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(max_length=2),
        ),
    ]
