# Generated by Django 4.1.7 on 2023-04-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bookstore.category')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.ImageField(upload_to='books_photos')),
                ('status', models.IntegerField(choices=[(0, 'Yangi'), (1, 'Qabul qilingan'), (2, 'Inkor qiligan')])),
                ('rating_stars', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('availability', models.BooleanField(default=False)),
                ('read', models.IntegerField()),
                ('reading', models.IntegerField()),
                ('will_read', models.IntegerField()),
                ('publish_year', models.IntegerField(blank=True, default=None, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(to='bookstore.authors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookstore.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookstore.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookstore.language')),
            ],
        ),
    ]
