# Generated by Django 4.2.2 on 2023-06-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='will_read',
            field=models.IntegerField(default=0),
        ),
    ]
